ALTER TABLE club_memberships
MODIFY COLUMN member_role ENUM(
  'PRESIDENT',
  'VICE_PRESIDENT',
  'SECRETARY',
  'TREASURER',
  'EDITOR',
  'EVENT_COORDINATOR',
  'SPORTS_COORDINATOR',
  'TECHNICAL_COORDINATOR',
  'ACADEMIC_COORDINATOR',
  'MEDIA_COORDINATOR',
  'GENERAL_MEMBER'
) NOT NULL;
